/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppInvalid {
    }
    interface AppRoot {
    }
    interface AppValid {
    }
}
declare global {
    interface HTMLAppInvalidElement extends Components.AppInvalid, HTMLStencilElement {
    }
    var HTMLAppInvalidElement: {
        prototype: HTMLAppInvalidElement;
        new (): HTMLAppInvalidElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppValidElement extends Components.AppValid, HTMLStencilElement {
    }
    var HTMLAppValidElement: {
        prototype: HTMLAppValidElement;
        new (): HTMLAppValidElement;
    };
    interface HTMLElementTagNameMap {
        "app-invalid": HTMLAppInvalidElement;
        "app-root": HTMLAppRootElement;
        "app-valid": HTMLAppValidElement;
    }
}
declare namespace LocalJSX {
    interface AppInvalid {
    }
    interface AppRoot {
    }
    interface AppValid {
    }
    interface IntrinsicElements {
        "app-invalid": AppInvalid;
        "app-root": AppRoot;
        "app-valid": AppValid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-invalid": LocalJSX.AppInvalid & JSXBase.HTMLAttributes<HTMLAppInvalidElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-valid": LocalJSX.AppValid & JSXBase.HTMLAttributes<HTMLAppValidElement>;
        }
    }
}
